extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  project: './tsconfig.json'
  tsconfigRootDir: .
  sourceType: 'module'

plugins:
  - "@typescript-eslint"
  - import
  - jest

settings:
  import/resolver:
    typescript:
      project: './tsconfig.json'


rules:
  no-use-before-define: off
  no-shadow: off
  no-restricted-imports:
    - error
    - patterns:
        - '../*'
        - './*'

  "@typescript-eslint/no-inferrable-types": off
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-shadow":
    - error
  "@typescript-eslint/no-use-before-define":
    - error
env:
  jest/globals: true
  node: true

ignorePatterns:
  - 'test/**/*'
