extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - jest
rules:
  no-use-before-define: off
  no-shadow: off

  "@typescript-eslint/no-inferrable-types": off
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-shadow":
    - error
  "@typescript-eslint/no-use-before-define":
    - error
env:
  jest/globals: true
  node: true
