proxy:
  host: "http://192.168.0.1:8888"  # Host for traffic proxy

api:
  auth:
    enabled: true
    username: 'admin'
    password: 'admin'

metrics:
  enabled: true
  auth:
    enabled: false
    username: 'admin'
    password: 'admin'

wafMiddleware:
  detectClientIp:
    headers: ['fastly-client-ip', 'cf-connecting-ip', 'x-original-forwarded-for', ]

  detectClientCountry:
    method: header
    header: 'X-client-country'

  detectClientCity:
    method: header
    header: 'X-client-city'


jailManager:
  # syncInterval: 5000
  # syncAlways: true
  storage:
    driver: file # or memory
    driverConfig:
      filePath: data/blocked_ips.json
      locker:
        enabled: true
        config:
          retries: 3

whitelist:
  ips: ['10.0.0.1', '10.0.0.2'] # OPTIONAL
  ipSubnet: ['192.168.0.0/22', '10.0.0.0/22'] # OPTIONAL
  geoCountry: ['USA', 'CA'] # OPTIONAL
  geoCity: ['Lviv'] # OPTIONAL

rules:
  - type: "static"
    linkUrl: "https://httpbin.org/status/200"
    updateInterval: 120000

  - type: "composite"
    keys: ["ip", "user-agent", "hostname", "url", "geo-country", "geo-city"]
    conditions:
      - field: 'url' # or hostname, user-agent, header-<header-name>, geo-country, geo-city
        method: 'equals'
        values: [ "/admin.php" ]

      - field: 'url' # or hostname, user-agent, header-<header-name>, geo-country, geo-city
        method: 'regexp'
        values: ["/wp-(admin|include|content)/i"]

    period: 60             # Period in seconds for which the number of requests is considered
    limit: 5               # If during the period the number of requests exceeds the limit, ban
    duration: 180          # Blocking by 180 seconds when the limit exceeds
    escalationRate: 1.3     # OPTIONAL


  - type: "flexible"
    conditions:
      - field: 'url' # or hostname, user-agent, header-<header-name>, geo-country, geo-city
        method: 'equals'
        values: [ "/admin.php" ]

      - field: 'url' # or hostname, user-agent, header-<header-name>, geo-country, geo-city
        method: 'regexp'
        values: ["/wp-(admin|include|content)/i"]



    period: 60            # Period in seconds for which the number of requests is considered
    limit: 5              # If during the period the number of requests exceeds the limit, ban
    duration: 180         # Blocking by 180 seconds when the limit exceeds
    escalationRate: 1.1   # OPTIONAL
